### ISSUE TITLE
Elección de las herramientas a usar

### ISSUE THREAD

**Issue by PedroMFC** [tdd-organization-afp/tdd-provisional#7]
En este *issue* se van a tratar las principales herramientas para usar en el proyecto. Hay que seleccionar una herramienta de *logging*, otra de configuración remota y las adicionales necesarias.

**Comment by PedroMFC** [comment]
Bueno, yo creo que para el tema de *logging* podemos usar logstach, que es gratuita. Y para la configuración remota si hiciera falta propongo etcd, aunque he mirado alternativas y pone que pueden ser MongoDB o Zookeeper.

**Comment by dylan-nogueras** [comment]
Como lenguaje quizás podríamos usar Python. He encontrado un tutorial de Flask, un microframework que permite desarrollar aplicaciones web con este lenguaje: https://j2logo.com/tutorial-flask-espanol/ Además, Python tiene un módulo de _logging_.

**Comment by PedroMFC** [comment]
Perfecto, lo de flask si nos decimos por hacerlo en web está súper bien. Lo del logging interno de Python también lo vi, aunque a lo mejor se puede completar con el que he puesto antes y usar los dos.

**Comment by dylan-nogueras** [comment]
Genial, ya vamos decidiendo qué va mejor.

**Comment by morevi** [comment]
Estoy probando Vincent, [ esta librería ](https://vincent.readthedocs.io/en/latest/index.html) de python parece bastante útil para hacer las gráficas y representar la información en mapas.

**Comment by PedroMFC** [comment]
Ok, yo he visto [esta](https://www.google.com/amp/www.geomapik.com/desarrollo-programacion-gis/mapas-con-python-geopandas-matplotlib/amp/) que también puede ser interesante a la hora de generar gráficos de mapas

**Comment by morevi** [comment]
@PedroMFC utilizando esa herramienta he conseguido dibujar un mapa por municipios de cádiz
![Figure_1](https://user-images.githubusercontent.com/32617125/92655607-ff26e280-f2f1-11ea-8684-d74f3ef3e35a.png)

**Comment by PedroMFC** [comment]
Fantástico. A modo de resumen de lo que hemos hablado:
* Lenguaje: `Python`.
* *Logging*: mecanismo interno del lenguje, `Logstach`.
* Configuración remota: `etcd`.
* Aplicación web: `Flask`.
* Gráficas: `Matplotlib` y `Geopandas`.

Qué os parece si incluimos esas por ahora y ya según las necesidades que tengamos discutimos otras tecnologías.

**Comment by dylan-nogueras** [comment]
Perfecto, incluido en el README y solicitado `pull request.`
